disabled_rules:
- function_parameter_count
- nesting
- variable_name
- weak_delegate
- trailing_comma
- trailing_whitespace
- force_unwrapping
- force_cast
opt_in_rules:
- empty_count
- private_outlet
warning_threshold: 15
line_length: 150
file_length:
warning: 500
type_body_length:
warning: 400
error: 450
excluded:
- Carthage/
- Frameworks/
- Pods
reporter: "xcode"

